# .github/workflows/release.yml
name: release-myspeed
on:
  workflow_dispatch:
  push:
    branches: []

jobs:
  release-myspeed:
    permissions:
      contents: write

    uses: ./.github/workflows/bin-release.yml
    with:
      PACKAGE_NAME: "myspeed"
