# .github/workflows/release.yml
name: release-myspeed
on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  release-myspeed:
    - uses: PyO3/maturin-action@v1
      with:
        command: build
        args: --release
